import { useState, useEffect } from 'react';
import Anthropic from '@anthropic-ai/sdk';
import { getNights, formatDate } from '../utils';

const client = new Anthropic({
  apiKey: import.meta.env.VITE_ANTHROPIC_API_KEY,
  dangerouslyAllowBrowser: true,
});

const TRAVELLER_LABELS = {
  business: 'business travellers',
  'adult-leisure': 'adult leisure travellers',
  family: 'families with children',
};

function ActivityCard({ title, description }) {
  return (
    <div className="border border-slate-200 rounded-lg p-4">
      <h4 className="font-medium text-slate-900 mb-1">{title}</h4>
      <p className="text-sm text-slate-600">{description}</p>
    </div>
  );
}

function ActivitiesSection({ hotel, travellerType }) {
  const [activities, setActivities] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    setActivities(null);
    setLoading(true);
    setError(null);

    const travellerLabel = TRAVELLER_LABELS[travellerType] || 'travellers';

    client.messages
      .create({
        model: 'claude-opus-4-7',
        max_tokens: 512,
        messages: [
          {
            role: 'user',
            content:
              `You are a Las Vegas activities expert. Suggest exactly 2 activities in or near ` +
              `${hotel.name} (${hotel.location}) that are ideal for ${travellerLabel}. ` +
              `Return ONLY a JSON array — no markdown, no explanation — with exactly 2 objects, ` +
              `each having a "title" (string) and "description" (1–2 sentences, string) field.`,
          },
        ],
      })
      .then((response) => {
        const text = response.content.find((b) => b.type === 'text')?.text ?? '';
        const parsed = JSON.parse(text);
        setActivities(Array.isArray(parsed) ? parsed : parsed.activities ?? []);
      })
      .catch(() => {
        setError('Could not load activity suggestions.');
      })
      .finally(() => {
        setLoading(false);
      });
  }, [hotel.id, travellerType]);

  return (
    <div className="mt-6 pt-6 border-t border-slate-100">
      <h3 className="font-semibold text-slate-900 mb-3">
        Suggested nearby activities
        {travellerType && TRAVELLER_LABELS[travellerType] && (
          <span className="text-sm font-normal text-slate-500 ml-2">
            for {TRAVELLER_LABELS[travellerType]}
          </span>
        )}
      </h3>

      {loading && (
        <div className="space-y-3">
          {[0, 1].map((i) => (
            <div key={i} className="border border-slate-200 rounded-lg p-4 animate-pulse">
              <div className="h-4 bg-slate-200 rounded w-2/5 mb-2" />
              <div className="h-3 bg-slate-100 rounded w-full mb-1" />
              <div className="h-3 bg-slate-100 rounded w-3/4" />
            </div>
          ))}
        </div>
      )}

      {error && <p className="text-sm text-slate-400">{error}</p>}

      {activities && (
        <div className="space-y-3">
          {activities.map((a, i) => (
            <ActivityCard key={i} title={a.title} description={a.description} />
          ))}
          <p className="text-xs text-slate-400 mt-1">Suggestions generated by Claude AI</p>
        </div>
      )}
    </div>
  );
}

export default function AccommodationDetail({ hotel, searchParams, onBack }) {
  const nights = getNights(searchParams?.dateRange);
  const total = nights ? hotel.pricePerNight * nights : null;

  return (
    <div>
      <button
        type="button"
        onClick={onBack}
        className="mb-5 inline-flex items-center gap-1.5 text-sm text-blue-600 hover:text-blue-700 font-medium"
      >
        <span aria-hidden="true">←</span> Back to results
      </button>

      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
        {/* Hero image */}
        <div className="overflow-hidden" style={{ aspectRatio: '21/8' }}>
          <img
            src={hotel.image}
            alt={hotel.name}
            className="w-full h-full object-cover"
          />
        </div>

        <div className="p-6 lg:p-8">
          <div className="flex flex-col lg:flex-row gap-8">

            {/* Main content */}
            <div className="flex-1 min-w-0">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 mb-2">
                <h2 className="text-2xl font-bold text-slate-900">{hotel.name}</h2>
                <div className="flex items-center gap-1.5 shrink-0">
                  <span className="text-amber-400 text-lg">★</span>
                  <span className="font-semibold text-slate-800">{hotel.rating}</span>
                  <span className="text-sm text-slate-400">({hotel.reviewCount.toLocaleString()} reviews)</span>
                </div>
              </div>

              <p className="text-sm text-slate-500 mb-4">{hotel.location}</p>
              <p className="text-slate-700 leading-relaxed mb-6">{hotel.description}</p>

              <h3 className="font-semibold text-slate-900 mb-3">Highlights</h3>
              <ul className="space-y-2 mb-6">
                {hotel.highlights.map((h) => (
                  <li key={h} className="flex items-start gap-2.5 text-sm text-slate-600">
                    <span className="text-blue-500 mt-0.5 shrink-0">✓</span>
                    {h}
                  </li>
                ))}
              </ul>

              <h3 className="font-semibold text-slate-900 mb-3">Amenities</h3>
              <div className="flex flex-wrap gap-2">
                {hotel.amenities.map((a) => (
                  <span key={a} className="text-sm bg-slate-100 text-slate-600 px-3 py-1 rounded-full">
                    {a}
                  </span>
                ))}
              </div>

              <ActivitiesSection hotel={hotel} travellerType={searchParams?.travellerType} />
            </div>

            {/* Booking sidebar */}
            <div className="lg:w-72 shrink-0">
              <div className="border border-slate-200 rounded-xl p-5 lg:sticky lg:top-6">
                <div className="text-2xl font-bold text-slate-900">
                  £{hotel.pricePerNight.toLocaleString()}
                  <span className="text-base font-normal text-slate-500"> / night</span>
                </div>

                {searchParams?.dateRange?.from && (
                  <div className="mt-3 text-sm text-slate-600 space-y-1">
                    <div className="flex justify-between">
                      <span className="text-slate-500">Check-in</span>
                      <span>{formatDate(searchParams.dateRange.from)}</span>
                    </div>
                    {searchParams.dateRange.to && (
                      <div className="flex justify-between">
                        <span className="text-slate-500">Check-out</span>
                        <span>{formatDate(searchParams.dateRange.to)}</span>
                      </div>
                    )}
                    {searchParams.guests > 0 && (
                      <div className="flex justify-between">
                        <span className="text-slate-500">Guests</span>
                        <span>{searchParams.guests}</span>
                      </div>
                    )}
                  </div>
                )}

                {total !== null && (
                  <div className="mt-3 pt-3 border-t border-slate-100 space-y-1 text-sm">
                    <div className="flex justify-between text-slate-600">
                      <span>£{hotel.pricePerNight} × {nights} {nights === 1 ? 'night' : 'nights'}</span>
                      <span>£{total.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between font-semibold text-slate-900 pt-2 border-t border-slate-100">
                      <span>Total</span>
                      <span>£{total.toLocaleString()}</span>
                    </div>
                  </div>
                )}

                <button
                  type="button"
                  className="w-full mt-4 py-3 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 active:bg-blue-800 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  Reserve now
                </button>
                <p className="text-xs text-slate-400 text-center mt-2">No charge until confirmation</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
